# 1. Create the Project
apiVersion: project.cci.vmware.com/v1alpha2
kind: Project
metadata:
  name: my-dev-project-01
spec:
  description: "Sample VCF 9 Project"
---
# 2. Add rax-user-1 as Admin
apiVersion: authorization.cci.vmware.com/v1alpha1
kind: ProjectRoleBinding
metadata:
  name: "cci:user:rax-user-1"
  namespace: my-dev-project-01
roleRef:
  apiGroup: authorization.cci.vmware.com
  kind: ProjectRole
  name: admin
subjects:
- kind: User
  name: rax-user-1
---
# 3. Create the Supervisor Namespace (CCI Infrastructure)
apiVersion: infrastructure.cci.vmware.com/v1alpha2
kind: SupervisorNamespace
metadata:
  generateName: my-dev-project-01-ns-
  namespace: my-dev-project-01
spec:
  description: "Sample VCF 9 Development Namespace"
  regionName: "region-us1-a"
  className: "xxlarge"
  vpcName: "region-us1-a-default-vpc"
  initialClassConfigOverrides:
    zones:
    - name: "zone-vmw-lab1-md-cl01"
      cpuLimit: "100000M"
      cpuReservation: "0M"
      memoryLimit: "102400Mi"
      memoryReservation: "0Mi"